### ISSUE TITLE
NoMethodError - undefined method 'string_literal' for #<String:0x...>:

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/bel_parser#75]
```
NoMethodError - undefined method `string_literal' for #<String:0x170b8028>:
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state/set.rb:63:in `handle_annotation'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state/set.rb:39:in `consume'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state_aggregator.rb:22:in `block in each'
        org/jruby/RubyArray.java:1593:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state_aggregator.rb:21:in `block in each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/parsers/ast/node.rb:107:in `traverse'
        org/jruby/RubyEnumerator.java:293:in `each'
        org/jruby/RubyEnumerator.java:299:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state_aggregator.rb:20:in `block in each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/first_node.rb:13:in `block in each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/ast_filter.rb:15:in `block in each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/ast_generator.rb:63:in `block in each'
        org/jruby/RubyYielder.java:101:in `yield'
        org/jruby/RubyYielder.java:110:in `<<'
        uri:classloader:/jruby/kernel/enumerator.rb:72:in `block in map'
        uri:classloader:/jruby/kernel/enumerator.rb:24:in `block in initialize'
        org/jruby/RubyIO.java:3251:in `each_line'
        org/jruby/RubyEnumerator.java:293:in `each'
        org/jruby/RubyEnumerator.java:299:in `each'
        org/jruby/RubyEnumerator.java:293:in `each'
        org/jruby/RubyEnumerator.java:299:in `each'
        uri:classloader:/jruby/kernel/enumerator.rb:23:in `block in initialize'
        org/jruby/RubyKernel.java:1103:in `catch'
        uri:classloader:/jruby/kernel/enumerator.rb:22:in `block in initialize'
        org/jruby/RubyGenerator.java:102:in `each'
        org/jruby/RubyEnumerator.java:293:in `each'
        org/jruby/RubyEnumerator.java:299:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/ast_generator.rb:52:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/ast_filter.rb:13:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/filter.rb:28:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/first_node.rb:12:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/state_aggregator.rb:19:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/validator.rb:30:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel_parser/script/nanopub_mapper.rb:26:in `each'
        .../jruby-9.1.2.0/gems/gems/bel_parser-1.0.5-java/lib/bel/translator/plugins/bel_script/reader.rb:29:in `each'
        org/jruby/RubyEnumerator.java:293:in `each'
        org/jruby/RubyEnumerable.java:399:in `first'
        .../jruby-9.1.2.0/gems/gems/openbel-api-1.0.1-java/app/openbel/api/routes/datasets.rb:74:in `check_dataset'
        .../jruby-9.1.2.0/gems/gems/openbel-api-1.0.1-java/app/openbel/api/routes/datasets.rb:243:in `block in POST /api/datasets'
        org/jruby/RubyMethod.java:111:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block in route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block in route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        org/jruby/RubyArray.java:1593:in `each'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        org/jruby/RubyKernel.java:1103:in `catch'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        .../jruby/gems/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
        .../jruby/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
"POST /api/datasets HTTP/1.1" 500 30 47.7250
```

**Comment by abargnesi** [comment]
Nice work :tada:
